//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiveApp.DBFrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveFile
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdFolder { get; set; }
        public string Name { get; set; }
    
        public virtual Folder Folder { get; set; }
    }
}
